--- #YAML:1.0
name:               Math-PlanePath-Toothpick
version:            11
abstract:           Toothpick and other cellular automaton mathematical paths through the 2-D plane.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    constant:             1.02
    Math::PlanePath:      106
    Math::PlanePath::Base::Digits:  91
    Math::PlanePath::Base::Generic:  91
    perl:                 5.004
    Test:                 0
resources:
    homepage:  http://user42.tuxfamily.org/math-planepath/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
        - xt
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            Data::Float:         0
            Math::BigFloat:      1.993
            Math::BigInt:        0
            Math::BigInt::Lite:  0
            Math::BigRat:        0
